package api_tests

import (
	"bytes"
	"io"
	"mime/multipart"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// truncatedPNG is a minimal PNG header (8-byte signature + partial IHDR chunk)
// without IDAT or IEND — image.Decode must fail on it.
var truncatedPNG = []byte{
	0x89, 'P', 'N', 'G', '\r', '\n', 0x1a, '\n',
	0x00, 0x00, 0x00, 0x0D, 'I', 'H', 'D', 'R',
	0x00, 0x00, 0x00, 0xc8, 0x00, 0x00, 0x00, 0xc8,
	0x08, 0x02, 0x00, 0x00, 0x00,
	// Truncated — no IDAT, no IEND, no trailing CRC table.
}

// validSmallPNG is a valid 1×1 RGB PNG generated by image/png encoder.
var validSmallPNG = []byte{
	0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44, 0x52,
	0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x02, 0x00, 0x00, 0x00, 0x90, 0x77, 0x53,
	0xDE, 0x00, 0x00, 0x00, 0x10, 0x49, 0x44, 0x41, 0x54, 0x78, 0x9C, 0x62, 0xFA, 0xCF, 0xC0, 0x00,
	0x08, 0x00, 0x00, 0xFF, 0xFF, 0x03, 0x09, 0x01, 0x02, 0x58, 0xB6, 0xD5, 0x50, 0x00, 0x00, 0x00,
	0x00, 0x49, 0x45, 0x4E, 0x44, 0xAE, 0x42, 0x60, 0x82,
}

// TestImageIngestion_RejectsTruncatedPNG verifies BH-011:
// uploading a truncated / undecodable PNG must be rejected with 400.
func TestImageIngestion_RejectsTruncatedPNG(t *testing.T) {
	tc := SetupTestEnv(t)

	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)
	part, err := writer.CreateFormFile("resource", "bh011-truncated.png")
	require.NoError(t, err)
	_, err = io.Copy(part, bytes.NewReader(truncatedPNG))
	require.NoError(t, err)
	require.NoError(t, writer.WriteField("Name", "bh011-truncated"))
	require.NoError(t, writer.WriteField("ContentType", "image/png"))
	require.NoError(t, writer.Close())

	req, err := http.NewRequest(http.MethodPost, "/v1/resource", body)
	require.NoError(t, err)
	req.Header.Set("Content-Type", writer.FormDataContentType())
	req.Header.Set("Accept", "application/json")

	rr := httptest.NewRecorder()
	tc.Router.ServeHTTP(rr, req)

	assert.Equal(t, http.StatusBadRequest, rr.Code, "truncated image must be rejected with 400")
	assert.Contains(t, rr.Body.String(), "decode", "error message must reference decode failure")
}

// TestImageIngestion_AcceptsValidImage verifies that a well-formed PNG still succeeds (regression guard).
func TestImageIngestion_AcceptsValidImage(t *testing.T) {
	tc := SetupTestEnv(t)

	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)
	part, err := writer.CreateFormFile("resource", "bh011-valid.png")
	require.NoError(t, err)
	_, err = io.Copy(part, bytes.NewReader(validSmallPNG))
	require.NoError(t, err)
	require.NoError(t, writer.WriteField("Name", "bh011-valid"))
	require.NoError(t, writer.WriteField("ContentType", "image/png"))
	require.NoError(t, writer.Close())

	req, err := http.NewRequest(http.MethodPost, "/v1/resource", body)
	require.NoError(t, err)
	req.Header.Set("Content-Type", writer.FormDataContentType())
	req.Header.Set("Accept", "application/json")

	rr := httptest.NewRecorder()
	tc.Router.ServeHTTP(rr, req)

	assert.Equal(t, http.StatusOK, rr.Code, "valid image must still succeed")
}
