package application_context

import (
	"errors"
	"fmt"

	"mahresources/auth"
	"mahresources/models"
)

// EnsureRootAdmin guarantees at least one enabled admin exists. If one already
// does, it only warms the actor cache and returns it. Otherwise it creates a
// "root" admin with a crypto-random password (marked PasswordAutoGenerated so
// the lockout warning can fire). It never hijacks a real account: it reuses an
// existing "root" only when that account is already an admin; if "root" is taken
// by a non-admin it suffixes root2, root3, … until it finds an unused name.
//
// Auto-create is invoked only from main.go so a fresh NewMahresourcesContext
// stays at zero users (TestCountUsersAndBootstrap).
func (ctx *MahresourcesContext) EnsureRootAdmin() (*models.User, error) {
	n, err := ctx.CountEnabledAdmins()
	if err != nil {
		return nil, err
	}
	if n > 0 {
		ctx.refreshRootAdmin() // warm the actor cache
		return ctx.RootAdmin()
	}

	password, err := auth.GenerateToken() // crypto-random, satisfies ValidatePassword
	if err != nil {
		return nil, err
	}
	hash, err := auth.HashPassword(password)
	if err != nil {
		return nil, err
	}

	user, err := ctx.createOrReuseRootAdmin(hash)
	if err != nil {
		return nil, err
	}
	ctx.refreshRootAdmin()
	return user, nil
}

// createOrReuseRootAdmin resolves the account to promote to the auto-generated
// root admin. It reuses "root" only if it is already an admin (re-enable + reset
// to an auto-generated password); if "root" is a non-admin it does not hijack it
// and instead creates the first unused rootN name.
func (ctx *MahresourcesContext) createOrReuseRootAdmin(hash string) (*models.User, error) {
	existing, err := ctx.GetUserByUsername("root")
	if err != nil && !errors.Is(err, ErrUserNotFound) {
		return nil, err
	}
	if existing == nil {
		return ctx.createAutoRootAdmin("root", hash)
	}
	if existing.Role == models.RoleAdmin {
		existing.PasswordHash = hash
		existing.Disabled = false
		existing.ScopeGroupId = nil
		existing.PasswordAutoGenerated = true
		if sErr := ctx.db.Save(existing).Error; sErr != nil {
			return nil, sErr
		}
		return existing, nil
	}
	// "root" is a real non-admin account; find an unused rootN instead.
	for i := 2; i < 10000; i++ {
		name := fmt.Sprintf("root%d", i)
		u, gErr := ctx.GetUserByUsername(name)
		if gErr != nil && !errors.Is(gErr, ErrUserNotFound) {
			return nil, gErr
		}
		if u == nil {
			return ctx.createAutoRootAdmin(name, hash)
		}
	}
	return nil, errors.New("could not find an available root admin username")
}

// createAutoRootAdmin inserts a fresh enabled admin with an auto-generated
// password. Goes through ctx.db.Create so User.BeforeCreate assigns a GUID.
func (ctx *MahresourcesContext) createAutoRootAdmin(username, hash string) (*models.User, error) {
	user := &models.User{
		Username:              username,
		DisplayName:           "Root Administrator",
		PasswordHash:          hash,
		Role:                  models.RoleAdmin,
		Disabled:              false,
		PasswordAutoGenerated: true,
	}
	if err := ctx.db.Create(user).Error; err != nil {
		if isUniqueConstraintError(err) {
			return nil, ErrUsernameTaken
		}
		return nil, err
	}
	return user, nil
}

// CountEnabledAdminsWithRealPassword counts enabled admins whose password was
// set by an operator (not auto-generated). Drives the per-boot lockout warning:
// when this is 0 under -auth, the only credentials are unknown random ones.
func (ctx *MahresourcesContext) CountEnabledAdminsWithRealPassword() (int64, error) {
	var count int64
	if err := ctx.db.Model(&models.User{}).
		Where("role = ? AND disabled = ? AND password_auto_generated = ?", models.RoleAdmin, false, false).
		Count(&count).Error; err != nil {
		return 0, err
	}
	return count, nil
}
