package application_context

import (
	"errors"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"mahresources/models"

	"gorm.io/gorm"
)

func TestEnsureRootAdmin_FreshCreatesAutoGeneratedRoot(t *testing.T) {
	ctx := newStampTestContext(t, true)
	root, err := ctx.EnsureRootAdmin()
	if err != nil {
		t.Fatalf("EnsureRootAdmin: %v", err)
	}
	if root.Username != "root" {
		t.Errorf("expected username 'root', got %q", root.Username)
	}
	if root.Role != models.RoleAdmin || root.Disabled {
		t.Errorf("root must be an enabled admin, got role=%q disabled=%v", root.Role, root.Disabled)
	}
	if !root.PasswordAutoGenerated {
		t.Error("auto-created root must have PasswordAutoGenerated=true")
	}
	n, _ := ctx.CountEnabledAdmins()
	if n != 1 {
		t.Errorf("expected 1 enabled admin, got %d", n)
	}
}

func TestEnsureRootAdmin_ExistingAdminIsNoOp(t *testing.T) {
	ctx := newStampTestContext(t, true)
	boss := makeAdmin(t, ctx, "boss")
	got, err := ctx.EnsureRootAdmin()
	if err != nil {
		t.Fatalf("EnsureRootAdmin: %v", err)
	}
	if got.ID != boss.ID {
		t.Errorf("expected existing admin %d, got %d", boss.ID, got.ID)
	}
	total, _ := ctx.CountUsers()
	if total != 1 {
		t.Errorf("EnsureRootAdmin must not create a new user when an admin exists, got %d users", total)
	}
}

func TestEnsureRootAdmin_RootTakenByNonAdminSuffixes(t *testing.T) {
	ctx := newStampTestContext(t, true)
	// "root" is a real non-admin account — must not be hijacked.
	if _, err := ctx.CreateUser(&UserInput{Username: "root", Password: "password1", Role: models.RoleUser}); err != nil {
		t.Fatalf("create root user: %v", err)
	}
	created, err := ctx.EnsureRootAdmin()
	if err != nil {
		t.Fatalf("EnsureRootAdmin: %v", err)
	}
	if created.Username != "root2" {
		t.Errorf("expected suffixed 'root2', got %q", created.Username)
	}
	if created.Role != models.RoleAdmin {
		t.Errorf("root2 must be an admin, got %q", created.Role)
	}
	// The original non-admin "root" must be untouched.
	orig, err := ctx.GetUserByUsername("root")
	if err != nil {
		t.Fatalf("original root missing: %v", err)
	}
	if orig.Role != models.RoleUser {
		t.Errorf("original root must remain a non-admin, got %q", orig.Role)
	}
}

func TestEnsureRootAdmin_ReusesDisabledRootAdmin(t *testing.T) {
	ctx := newStampTestContext(t, true)
	// A disabled admin named "root" is the only admin → EnsureRootAdmin should
	// re-enable and reset it (reuse), not create root2.
	root, err := ctx.CreateUser(&UserInput{Username: "root", Password: "password1", Role: models.RoleAdmin, Disabled: true})
	if err != nil {
		t.Fatalf("create disabled root admin: %v", err)
	}
	oldSession, _, err := ctx.CreateSession(root.ID, time.Hour, "", "")
	if err != nil {
		t.Fatalf("create old session: %v", err)
	}
	oldToken, _, err := ctx.CreateApiToken(root.ID, "old", nil)
	if err != nil {
		t.Fatalf("create old token: %v", err)
	}
	got, err := ctx.EnsureRootAdmin()
	if err != nil {
		t.Fatalf("EnsureRootAdmin: %v", err)
	}
	if got.Username != "root" || got.Disabled {
		t.Errorf("expected re-enabled 'root', got username=%q disabled=%v", got.Username, got.Disabled)
	}
	total, _ := ctx.CountUsers()
	if total != 1 {
		t.Errorf("should reuse the existing root admin, not create a new one; got %d users", total)
	}
	if _, _, err := ctx.ValidateSession(oldSession); !errors.Is(err, ErrSessionInvalid) {
		t.Errorf("disabled root's old session survived password reset: %v", err)
	}
	if _, _, err := ctx.ValidateApiToken(oldToken); !errors.Is(err, ErrApiTokenInvalid) {
		t.Errorf("disabled root's old token survived password reset: %v", err)
	}
}

func TestEnsureAdminUserReclassifiesConcurrentRename(t *testing.T) {
	ctx := newSharedFileContext(t)
	existing, err := ctx.CreateUser(&UserInput{Username: "bootstrap", Password: "password1", Role: models.RoleEditor})
	if err != nil {
		t.Fatalf("create existing: %v", err)
	}
	paused := make(chan struct{})
	release := make(chan struct{})
	var used atomic.Bool
	ctx.identityReuseBarrier = func(operation string, expected *models.User) {
		if operation == "ensure-admin" && used.CompareAndSwap(false, true) {
			close(paused)
			<-release
		}
	}
	done := make(chan struct {
		user *models.User
		err  error
	}, 1)
	go func() {
		user, ensureErr := ctx.EnsureAdminUser("bootstrap", "new-password")
		done <- struct {
			user *models.User
			err  error
		}{user, ensureErr}
	}()
	<-paused
	if err := ctx.db.Model(&models.User{}).Where("id = ?", existing.ID).Update("username", "renamed-away").Error; err != nil {
		t.Fatalf("concurrent rename: %v", err)
	}
	close(release)
	result := <-done
	if result.err != nil {
		t.Fatalf("EnsureAdminUser: %v", result.err)
	}
	if result.user.Username != "bootstrap" || result.user.Role != models.RoleAdmin || result.user.Disabled {
		t.Fatalf("bootstrap did not converge on requested enabled admin: %+v", result.user)
	}
	moved, err := ctx.GetUser(existing.ID)
	if err != nil || moved.Username != "renamed-away" || moved.Role != models.RoleEditor {
		t.Fatalf("renamed identity was hijacked: user=%+v err=%v", moved, err)
	}
}

func TestEnsureRootAdminReclassifiesConcurrentStaleRole(t *testing.T) {
	ctx := newSharedFileContext(t)
	root, err := ctx.CreateUser(&UserInput{Username: "root", Password: "password1", Role: models.RoleAdmin, Disabled: true})
	if err != nil {
		t.Fatalf("create disabled root: %v", err)
	}
	paused := make(chan struct{})
	release := make(chan struct{})
	var used atomic.Bool
	ctx.identityReuseBarrier = func(operation string, expected *models.User) {
		if operation == "ensure-root" && used.CompareAndSwap(false, true) {
			close(paused)
			<-release
		}
	}
	done := make(chan struct {
		user *models.User
		err  error
	}, 1)
	go func() {
		user, ensureErr := ctx.EnsureRootAdmin()
		done <- struct {
			user *models.User
			err  error
		}{user, ensureErr}
	}()
	<-paused
	if err := ctx.db.Model(&models.User{}).Where("id = ?", root.ID).Update("role", models.RoleEditor).Error; err != nil {
		t.Fatalf("concurrent role change: %v", err)
	}
	close(release)
	result := <-done
	if result.err != nil {
		t.Fatalf("EnsureRootAdmin: %v", result.err)
	}
	if result.user.Username != "root2" || result.user.Role != models.RoleAdmin || result.user.Disabled {
		t.Fatalf("root bootstrap did not reclassify stale role: %+v", result.user)
	}
	original, err := ctx.GetUser(root.ID)
	if err != nil || original.Role != models.RoleEditor || !original.Disabled {
		t.Fatalf("stale root identity was re-enabled: user=%+v err=%v", original, err)
	}
}

func TestEnsureRootAdminConcurrentContextsConverge(t *testing.T) {
	ctx := newSharedFileContext(t)
	other := *ctx
	other.db = ctx.db.Session(&gorm.Session{NewDB: true})

	start := make(chan struct{})
	results := make(chan error, 2)
	var wg sync.WaitGroup
	for _, candidate := range []*MahresourcesContext{ctx, &other} {
		wg.Add(1)
		go func(c *MahresourcesContext) {
			defer wg.Done()
			<-start
			_, err := c.EnsureRootAdmin()
			results <- err
		}(candidate)
	}
	close(start)
	wg.Wait()
	close(results)
	for err := range results {
		if err != nil {
			t.Fatalf("concurrent EnsureRootAdmin: %v", err)
		}
	}
	if n, err := ctx.CountEnabledAdmins(); err != nil || n != 1 {
		t.Fatalf("enabled admins = %d, err=%v; want exactly one", n, err)
	}
}

func TestLockoutWarning_RealPasswordCount(t *testing.T) {
	ctx := newStampTestContext(t, true)
	root, err := ctx.EnsureRootAdmin()
	if err != nil {
		t.Fatalf("EnsureRootAdmin: %v", err)
	}
	// Only an auto-generated admin exists → the lockout warning would fire.
	if n, _ := ctx.CountEnabledAdminsWithRealPassword(); n != 0 {
		t.Errorf("expected 0 real-password admins, got %d", n)
	}
	// Setting a real password clears the marker → warning stops.
	if err := ctx.SetUserPassword(root.ID, "operator-set-password"); err != nil {
		t.Fatalf("SetUserPassword: %v", err)
	}
	if n, _ := ctx.CountEnabledAdminsWithRealPassword(); n != 1 {
		t.Errorf("expected 1 real-password admin after SetUserPassword, got %d", n)
	}
	reloaded, _ := ctx.GetUser(root.ID)
	if reloaded.PasswordAutoGenerated {
		t.Error("PasswordAutoGenerated must be cleared after a real password is set")
	}
}

// Phase 7: RootAdminPrincipal reports the oldest enabled admin's identity.
func TestRootAdminPrincipal_ReportsRootIdentity(t *testing.T) {
	ctx := newStampTestContext(t, false)
	boss := makeAdmin(t, ctx, "boss")
	p, err := ctx.RootAdminPrincipal()
	if err != nil {
		t.Fatalf("RootAdminPrincipal: %v", err)
	}
	if p.UserID != boss.ID || p.Username != "boss" || p.Role != models.RoleAdmin {
		t.Errorf("principal should report root identity, got id=%d username=%q role=%q", p.UserID, p.Username, p.Role)
	}
	if !p.SuperUser {
		t.Error("no-auth root principal must keep SuperUser=true")
	}
}
