package application_context

import (
	"testing"

	"mahresources/models"
)

func TestEnsureRootAdmin_FreshCreatesAutoGeneratedRoot(t *testing.T) {
	ctx := newStampTestContext(t, true)
	root, err := ctx.EnsureRootAdmin()
	if err != nil {
		t.Fatalf("EnsureRootAdmin: %v", err)
	}
	if root.Username != "root" {
		t.Errorf("expected username 'root', got %q", root.Username)
	}
	if root.Role != models.RoleAdmin || root.Disabled {
		t.Errorf("root must be an enabled admin, got role=%q disabled=%v", root.Role, root.Disabled)
	}
	if !root.PasswordAutoGenerated {
		t.Error("auto-created root must have PasswordAutoGenerated=true")
	}
	n, _ := ctx.CountEnabledAdmins()
	if n != 1 {
		t.Errorf("expected 1 enabled admin, got %d", n)
	}
}

func TestEnsureRootAdmin_ExistingAdminIsNoOp(t *testing.T) {
	ctx := newStampTestContext(t, true)
	boss := makeAdmin(t, ctx, "boss")
	got, err := ctx.EnsureRootAdmin()
	if err != nil {
		t.Fatalf("EnsureRootAdmin: %v", err)
	}
	if got.ID != boss.ID {
		t.Errorf("expected existing admin %d, got %d", boss.ID, got.ID)
	}
	total, _ := ctx.CountUsers()
	if total != 1 {
		t.Errorf("EnsureRootAdmin must not create a new user when an admin exists, got %d users", total)
	}
}

func TestEnsureRootAdmin_RootTakenByNonAdminSuffixes(t *testing.T) {
	ctx := newStampTestContext(t, true)
	// "root" is a real non-admin account — must not be hijacked.
	if _, err := ctx.CreateUser(&UserInput{Username: "root", Password: "password1", Role: models.RoleUser}); err != nil {
		t.Fatalf("create root user: %v", err)
	}
	created, err := ctx.EnsureRootAdmin()
	if err != nil {
		t.Fatalf("EnsureRootAdmin: %v", err)
	}
	if created.Username != "root2" {
		t.Errorf("expected suffixed 'root2', got %q", created.Username)
	}
	if created.Role != models.RoleAdmin {
		t.Errorf("root2 must be an admin, got %q", created.Role)
	}
	// The original non-admin "root" must be untouched.
	orig, err := ctx.GetUserByUsername("root")
	if err != nil {
		t.Fatalf("original root missing: %v", err)
	}
	if orig.Role != models.RoleUser {
		t.Errorf("original root must remain a non-admin, got %q", orig.Role)
	}
}

func TestEnsureRootAdmin_ReusesDisabledRootAdmin(t *testing.T) {
	ctx := newStampTestContext(t, true)
	// A disabled admin named "root" is the only admin → EnsureRootAdmin should
	// re-enable and reset it (reuse), not create root2.
	if _, err := ctx.CreateUser(&UserInput{Username: "root", Password: "password1", Role: models.RoleAdmin, Disabled: true}); err != nil {
		t.Fatalf("create disabled root admin: %v", err)
	}
	got, err := ctx.EnsureRootAdmin()
	if err != nil {
		t.Fatalf("EnsureRootAdmin: %v", err)
	}
	if got.Username != "root" || got.Disabled {
		t.Errorf("expected re-enabled 'root', got username=%q disabled=%v", got.Username, got.Disabled)
	}
	total, _ := ctx.CountUsers()
	if total != 1 {
		t.Errorf("should reuse the existing root admin, not create a new one; got %d users", total)
	}
}

func TestLockoutWarning_RealPasswordCount(t *testing.T) {
	ctx := newStampTestContext(t, true)
	root, err := ctx.EnsureRootAdmin()
	if err != nil {
		t.Fatalf("EnsureRootAdmin: %v", err)
	}
	// Only an auto-generated admin exists → the lockout warning would fire.
	if n, _ := ctx.CountEnabledAdminsWithRealPassword(); n != 0 {
		t.Errorf("expected 0 real-password admins, got %d", n)
	}
	// Setting a real password clears the marker → warning stops.
	if err := ctx.SetUserPassword(root.ID, "operator-set-password"); err != nil {
		t.Fatalf("SetUserPassword: %v", err)
	}
	if n, _ := ctx.CountEnabledAdminsWithRealPassword(); n != 1 {
		t.Errorf("expected 1 real-password admin after SetUserPassword, got %d", n)
	}
	reloaded, _ := ctx.GetUser(root.ID)
	if reloaded.PasswordAutoGenerated {
		t.Error("PasswordAutoGenerated must be cleared after a real password is set")
	}
}

// Phase 7: RootAdminPrincipal reports the oldest enabled admin's identity.
func TestRootAdminPrincipal_ReportsRootIdentity(t *testing.T) {
	ctx := newStampTestContext(t, false)
	boss := makeAdmin(t, ctx, "boss")
	p, err := ctx.RootAdminPrincipal()
	if err != nil {
		t.Fatalf("RootAdminPrincipal: %v", err)
	}
	if p.UserID != boss.ID || p.Username != "boss" || p.Role != models.RoleAdmin {
		t.Errorf("principal should report root identity, got id=%d username=%q role=%q", p.UserID, p.Username, p.Role)
	}
	if !p.SuperUser {
		t.Error("no-auth root principal must keep SuperUser=true")
	}
}
