package application_context

import (
	"errors"
	"fmt"

	"mahresources/auth"
	"mahresources/constants"
	"mahresources/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

// EnsureRootAdmin guarantees at least one enabled admin exists. If one already
// does, it only warms the actor cache and returns it. Otherwise it creates a
// "root" admin with a crypto-random password (marked PasswordAutoGenerated so
// the lockout warning can fire). It never hijacks a real account: it reuses an
// existing "root" only when that account is already an admin; if "root" is taken
// by a non-admin it suffixes root2, root3, … until it finds an unused name.
//
// Auto-create is invoked only from main.go so a fresh NewMahresourcesContext
// stays at zero users (TestCountUsersAndBootstrap).
func (ctx *MahresourcesContext) EnsureRootAdmin() (*models.User, error) {
	n, err := ctx.CountEnabledAdmins()
	if err != nil {
		return nil, err
	}
	if n > 0 {
		ctx.refreshRootAdmin() // warm the actor cache
		return ctx.RootAdmin()
	}

	password, err := auth.GenerateToken() // crypto-random, satisfies ValidatePassword
	if err != nil {
		return nil, err
	}
	hash, err := auth.HashPassword(password)
	if err != nil {
		return nil, err
	}

	user, err := ctx.createOrReuseRootAdmin(hash)
	if err != nil {
		// Another process may have won the startup race after our initial count.
		// Unique collisions (and transient losing writes) converge by accepting
		// the enabled administrator that is now authoritative.
		if winner, winnerErr := ctx.RootAdmin(); winnerErr == nil {
			ctx.refreshRootAdmin()
			return winner, nil
		}
		return nil, err
	}
	ctx.refreshRootAdmin()
	return user, nil
}

// createOrReuseRootAdmin resolves the account to promote to the auto-generated
// root admin. It reuses "root" only if it is already an admin (re-enable + reset
// to an auto-generated password); if "root" is a non-admin it does not hijack it
// and instead creates the first unused rootN name.
func (ctx *MahresourcesContext) createOrReuseRootAdmin(hash string) (*models.User, error) {
	for attempt := 0; attempt < 5; attempt++ {
		existing, err := ctx.GetUserByUsername("root")
		if err != nil && !errors.Is(err, ErrUserNotFound) {
			return nil, err
		}
		if existing == nil {
			created, createErr := ctx.createAutoRootAdmin("root", hash)
			if errors.Is(createErr, ErrUsernameTaken) {
				continue
			}
			return created, createErr
		}
		if ctx.identityReuseBarrier != nil {
			ctx.identityReuseBarrier("ensure-root", existing)
		}
		if existing.Role == models.RoleAdmin {
			reused, reuseErr := ctx.reuseExpectedRootAdmin(existing, hash)
			if errors.Is(reuseErr, errIdentityReclassified) {
				continue
			}
			return reused, reuseErr
		}

		// "root" is a real non-admin account; find an unused rootN instead.
		for i := 2; i < 10000; i++ {
			name := fmt.Sprintf("root%d", i)
			u, getErr := ctx.GetUserByUsername(name)
			if getErr != nil && !errors.Is(getErr, ErrUserNotFound) {
				return nil, getErr
			}
			if u == nil {
				created, createErr := ctx.createAutoRootAdmin(name, hash)
				if errors.Is(createErr, ErrUsernameTaken) {
					break
				}
				return created, createErr
			}
		}
	}
	return nil, errors.New("could not stabilize root administrator identity")
}

func (ctx *MahresourcesContext) reuseExpectedRootAdmin(expected *models.User, hash string) (*models.User, error) {
	var reused models.User
	err := ctx.db.Transaction(func(tx *gorm.DB) error {
		query := tx.Where("id = ? AND username = ? AND role = ?", expected.ID, "root", expected.Role)
		if ctx.Config.DbType == constants.DbTypeSqlite {
			res := tx.Exec("UPDATE users SET id = id WHERE id = ? AND username = ? AND role = ?", expected.ID, "root", expected.Role)
			if res.Error != nil {
				return res.Error
			}
			if res.RowsAffected == 0 {
				return errIdentityReclassified
			}
		} else if err := query.Clauses(clause.Locking{Strength: "UPDATE"}).First(&reused).Error; err != nil {
			if errors.Is(err, gorm.ErrRecordNotFound) {
				return errIdentityReclassified
			}
			return err
		}
		res := tx.Model(&models.User{}).
			Where("id = ? AND username = ? AND role = ?", expected.ID, "root", expected.Role).
			Updates(map[string]any{
				"password_hash": hash, "password_auto_generated": true,
				"disabled": false, "scope_group_id": nil,
			})
		if res.Error != nil {
			return res.Error
		}
		if res.RowsAffected == 0 {
			return errIdentityReclassified
		}
		if err := deleteUserSessions(tx, expected.ID, nil); err != nil {
			return err
		}
		if err := deleteUserAPITokens(tx, expected.ID); err != nil {
			return err
		}
		if err := tx.First(&reused, expected.ID).Error; err != nil {
			return err
		}
		if reused.Username != "root" || reused.Role != models.RoleAdmin || reused.Disabled {
			return errIdentityReclassified
		}
		return nil
	})
	return &reused, err
}

// createAutoRootAdmin inserts a fresh enabled admin with an auto-generated
// password. Goes through ctx.db.Create so User.BeforeCreate assigns a GUID.
func (ctx *MahresourcesContext) createAutoRootAdmin(username, hash string) (*models.User, error) {
	user := &models.User{
		Username:              username,
		DisplayName:           "Root Administrator",
		PasswordHash:          hash,
		Role:                  models.RoleAdmin,
		Disabled:              false,
		PasswordAutoGenerated: true,
	}
	if err := ctx.db.Create(user).Error; err != nil {
		if isUniqueConstraintError(err) {
			return nil, ErrUsernameTaken
		}
		return nil, err
	}
	return user, nil
}

// CountEnabledAdminsWithRealPassword counts enabled admins whose password was
// set by an operator (not auto-generated). Drives the per-boot lockout warning:
// when this is 0 under -auth, the only credentials are unknown random ones.
func (ctx *MahresourcesContext) CountEnabledAdminsWithRealPassword() (int64, error) {
	var count int64
	if err := ctx.db.Model(&models.User{}).
		Where("role = ? AND disabled = ? AND password_auto_generated = ?", models.RoleAdmin, false, false).
		Count(&count).Error; err != nil {
		return 0, err
	}
	return count, nil
}
