package application_context

import (
	"mahresources/auth"
	"mahresources/models"

	"gorm.io/gorm"
)

// SetUserPassword performs an administrator-style password reset. Every
// existing browser session and API token is revoked in the same transaction as
// the password replacement.
func (ctx *MahresourcesContext) SetUserPassword(id uint, newPassword string) error {
	hash, err := validatedPasswordHash(newPassword)
	if err != nil {
		return err
	}
	return ctx.db.Transaction(func(tx *gorm.DB) error {
		if err := replaceUserPassword(tx, id, hash, false); err != nil {
			return err
		}
		if err := deleteUserSessions(tx, id, nil); err != nil {
			return err
		}
		return deleteUserAPITokens(tx, id)
	})
}

// ChangeOwnPassword replaces a user's password while preserving at most the
// browser session making the request. A nil keepSessionTokenHash (including a
// bearer-authenticated request) revokes all browser sessions. API tokens remain
// valid for self-service password changes.
func (ctx *MahresourcesContext) ChangeOwnPassword(userID uint, newPassword string, keepSessionTokenHash *string) error {
	hash, err := validatedPasswordHash(newPassword)
	if err != nil {
		return err
	}
	return ctx.db.Transaction(func(tx *gorm.DB) error {
		if err := replaceUserPassword(tx, userID, hash, false); err != nil {
			return err
		}
		return deleteUserSessions(tx, userID, keepSessionTokenHash)
	})
}

func validatedPasswordHash(password string) (string, error) {
	if password == "" {
		return "", ErrPasswordRequired
	}
	if err := auth.ValidatePassword(password); err != nil {
		return "", err
	}
	return auth.HashPassword(password)
}

func replaceUserPassword(tx *gorm.DB, userID uint, hash string, autoGenerated bool) error {
	res := tx.Model(&models.User{}).Where("id = ?", userID).Updates(map[string]any{
		"password_hash":           hash,
		"password_auto_generated": autoGenerated,
	})
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return ErrUserNotFound
	}
	return nil
}

func deleteUserSessions(tx *gorm.DB, userID uint, keepTokenHash *string) error {
	query := tx.Where("user_id = ?", userID)
	if keepTokenHash != nil {
		query = query.Where("token_hash <> ?", *keepTokenHash)
	}
	return query.Delete(&models.Session{}).Error
}

func deleteUserAPITokens(tx *gorm.DB, userID uint) error {
	return tx.Where("user_id = ?", userID).Delete(&models.ApiToken{}).Error
}
