import { test, expect } from '../../fixtures/base.fixture';
import { MRQLPage } from '../../pages/MRQLPage';
import path from 'path';

test('MRQL paging retains keyboard focus, including at the first and last pages', async ({page,apiClient}) => {
    const prefix = `shared-focus-${Date.now()}`;
    const noteType = await apiClient.createNoteType(prefix);
    for (let i = 0; i < 11; i++) await apiClient.createNote({name:`${prefix} ${i}`,noteTypeId:noteType.ID});
    const mrql = new MRQLPage(page);
    await mrql.navigate();
    await mrql.enterQuery(`type = note AND name ~ "${prefix}" ORDER BY name ASC LIMIT 11`);
    await mrql.executeQuery();
    const size = page.getByLabel('Per page', {exact:false});
    await size.focus();
    await size.selectOption('5');
    await expect(page.locator('.note-card')).toHaveCount(5);
    await expect(size).toBeFocused();
    const next = page.getByRole('button', {name:'Next',exact:true});
    const previous = page.getByRole('button', {name:'Previous',exact:true});
    const status = page.locator('[data-mrql-page-status]');
    await next.focus();
    await next.press('Enter');
    await expect(status).toContainText('Page 2');
    await expect(next).toBeFocused();
    await next.press('Enter');
    await expect(status).toContainText('Page 3');
    await expect(status).toBeFocused();
    await previous.focus();
    await previous.press('Enter');
    await expect(status).toContainText('Page 2');
    await expect(previous).toBeFocused();
    await previous.press('Enter');
    await expect(status).toContainText('Page 1');
    await expect(status).toBeFocused();
});

test('MRQL selects types independently, uses Mass Edit fields, and clears on paging', async ({page,apiClient}) => {
    const errors: string[]=[];
    page.on('pageerror',err=>errors.push(err.message));
    const prefix=`shared-list-${Date.now()}`;
    const category=await apiClient.createCategory(prefix);
    const noteType=await apiClient.createNoteType(prefix);
    await apiClient.createGroup({name:prefix+' group',categoryId:category.ID});
    for(let i=0;i<7;i++) await apiClient.createNote({name:prefix+` note ${i}`,noteTypeId:noteType.ID});
    const mrql=new MRQLPage(page);
    await mrql.navigate();await mrql.enterQuery(`name ~ "${prefix}" ORDER BY name ASC LIMIT 8`);await mrql.executeQuery();
    const notes=page.locator('[data-selection-scope="mrql-note"]');
    const groups=page.locator('[data-selection-scope="mrql-group"]');
    await expect(notes.locator('.note-card')).toHaveCount(7);
    await notes.locator('.card-checkbox').first().check();
    await expect(notes.getByRole('button',{name:'Mass Edit Selected',exact:true})).toBeVisible();
    await expect(groups.locator('.card-checkbox')).not.toBeChecked();
    await notes.getByRole('button',{name:'Mass Edit Selected',exact:true}).click();
    const modal=page.getByRole('dialog',{name:'Mass edit notes'});
    await expect(modal).toBeVisible();
    await expect(modal.getByLabel('Related resources operation')).toBeVisible();
    await expect(modal.getByLabel('Related notes operation')).not.toBeVisible();
    await modal.getByRole('button',{name:'Cancel',exact:true}).click();
    await groups.getByRole('button',{name:'Mass edit all results',exact:true}).click();
    const groupModal = page.getByRole('dialog',{name:'Mass edit groups'});
    await expect(groupModal.getByRole('radio',{name:'Selected items (0)',exact:true})).toBeVisible();
    await groupModal.getByRole('button',{name:'Cancel',exact:true}).click();
    await page.getByLabel('Per page',{exact:false}).selectOption('5');
    await expect(notes.locator('.note-card')).toHaveCount(4);
    await expect(notes.locator('.card-checkbox:checked')).toHaveCount(0);
    await notes.locator('.card-checkbox').first().check();
    await page.getByRole('button',{name:'Next',exact:true}).click();
    await expect(notes.locator('.note-card')).toHaveCount(3);
    await expect(notes.locator('.card-checkbox:checked')).toHaveCount(0);
    expect(errors).toEqual([]);
});

test('MRQL Mass Edit applies within the query cap and refreshes the executed query', async ({page,apiClient,request}) => {
    const errors:string[]=[];page.on('pageerror',err=>errors.push(err.message));
    const prefix=`shared-mutation-${Date.now()}`;
    const noteType=await apiClient.createNoteType(prefix);
    const tag=await apiClient.createTag(prefix);
    const first=await apiClient.createNote({name:prefix+' A',noteTypeId:noteType.ID});
    const second=await apiClient.createNote({name:prefix+' B',noteTypeId:noteType.ID});
    const mrql=new MRQLPage(page);await mrql.navigate();
    await mrql.enterQuery(`type = note AND name ~ "${prefix}" ORDER BY name ASC LIMIT 1`);await mrql.executeQuery();
    await mrql.enterQuery('name = "unexecuted draft"');
    const notes=page.locator('[data-selection-scope="mrql-note"]');
    await notes.getByRole('button',{name:'Mass edit all results',exact:true}).click();
    const dialog=page.getByRole('dialog',{name:'Mass edit notes',exact:true});
    await dialog.getByRole('combobox',{name:'Tags to apply',exact:true}).fill(prefix);
    await page.getByRole('option').filter({hasText:prefix}).first().click();
    await dialog.getByRole('button',{name:'Apply',exact:true}).click();
    const confirmation=page.getByRole('alertdialog',{name:'Mass edit',exact:true});
    await expect(confirmation).toContainText('1 notes');
    await confirmation.getByRole('button',{name:'Apply',exact:true}).click();
    await expect(dialog).not.toBeVisible();
    await expect(notes.locator('.note-card')).toHaveCount(1);
    await expect(notes.locator('.note-card')).toContainText(prefix+' A');
    const response=await request.post('/v1/mrql',{data:{query:`type = note AND tags = "${prefix}"`}});
    const result=await response.json();
    expect(result.notes.map((note:{ID:number})=>note.ID)).toEqual([first.ID]);
    expect(result.notes.map((note:{ID:number})=>note.ID)).not.toContain(second.ID);
    await expect(mrql.editorContainer).toContainText('unexecuted draft');
    expect(errors).toEqual([]);
});

test('registered plugin actions appear in ordinary lists and MRQL and refresh in place', async ({page,apiClient}) => {
    await apiClient.enablePlugin('test-actions');
    const prefix=`shared-plugin-${Date.now()}`;
    const category=await apiClient.createCategory(prefix);
    const group=await apiClient.createGroup({name:prefix,categoryId:category.ID});
    await page.goto(`/groups?Name=${prefix}`);
    await page.getByRole('checkbox',{name:`Select ${prefix}`,exact:true}).check();
    await expect(page.getByRole('button',{name:'Group Action',exact:true})).toBeVisible();
    const mrql=new MRQLPage(page);await mrql.navigate();
    await mrql.enterQuery(`type = group AND id = ${group.ID}`);await mrql.executeQuery();
    const groups=page.locator('[data-selection-scope="mrql-group"]');
    await groups.locator('.card-checkbox').check();
    await expect(groups.getByRole('button',{name:'Compare',exact:true})).toBeDisabled();
    await expect(groups.getByText('Select exactly 2 items to compare.',{exact:true})).toBeVisible();
    await groups.getByRole('button',{name:'Group Action',exact:true}).click();
    const dialog=page.getByRole('dialog',{name:'Group Action',exact:true});
    await expect(dialog).toBeVisible();
    await dialog.getByRole('button',{name:'Run',exact:true}).click();
    await expect(dialog.getByRole('status')).toContainText(`Ran on group ${group.ID}`);
    await expect(dialog).not.toBeVisible();
    await expect(groups.locator('.card-checkbox')).not.toBeChecked();
    await expect(page).toHaveURL(/\/mrql/);
});

test('bucket appearances share selection and a built-in mutation refreshes every appearance', async ({page,apiClient},testInfo) => {
    const errors:string[]=[];page.on('pageerror',err=>errors.push(err.message));
    const prefix=`shared-buckets-${Date.now()}`;
    const type=await apiClient.createNoteType(prefix);
    const a=await apiClient.createTag(prefix+' A');
    const b=await apiClient.createTag(prefix+' B');
    const c=await apiClient.createTag(prefix+' C');
    const note=await apiClient.createNote({name:prefix,noteTypeId:type.ID});
    await apiClient.addTagsToNotes([note.ID],[a.ID,b.ID]);
    const mrql=new MRQLPage(page);await mrql.navigate();
    await mrql.enterQuery(`type = note AND id = ${note.ID} GROUP BY tags LIMIT 1`);await mrql.executeQuery();
    const notes=page.locator('[data-selection-scope="mrql-note"]');
    await expect(notes.locator('.note-card')).toHaveCount(2);
    await notes.locator('.card-checkbox').first().check();
    await expect(notes.locator('.card-checkbox:checked')).toHaveCount(2);
    await expect(notes.getByText('1 note selected',{exact:true})).toBeVisible();
    await notes.getByRole('button',{name:'Toggle Add Tag editor',exact:true}).click();
    const form=notes.locator('form[action*="/v1/notes/addTags"]');
    await form.getByRole('combobox',{name:'Add Tag',exact:true}).fill(prefix+' C');
    await page.getByRole('option').filter({hasText:prefix+' C'}).click();
    await form.getByRole('button',{name:'Add',exact:true}).click();
    await expect(notes.locator('.note-card')).toHaveCount(3);
    await expect(notes.locator('.card-checkbox:checked')).toHaveCount(0);
    await notes.locator('.card-checkbox').first().check();
    await notes.getByRole('button',{name:'Toggle Add Tag editor',exact:true}).click();
    await expect(notes.locator('form[action*="/v1/notes/addTags"]')).toBeVisible();
    await expect(notes.locator('form[action*="/v1/notes/removeTags"]')).not.toBeVisible();
    await expect.poll(() => form.evaluate(el => el.clientHeight >= el.scrollHeight)).toBe(true);
    await notes.screenshot({path:testInfo.outputPath('shared-bucket-actions.png')});
    expect(errors).toEqual([]);
});


test('lightbox writes refresh MRQL and ordinary selection metadata', async ({page,apiClient}) => {
    const prefix = `review-lightbox-${Date.now()}`;
    const resource = await apiClient.createResource({name:prefix, filePath:path.join(__dirname,'../../test-assets/sample-image-34.png')});
    await page.goto(`/resources?Ids=${resource.ID}`);
    await page.getByRole('checkbox',{name:`Select ${prefix}`,exact:true}).check();
    await page.locator(`[data-lightbox-item][data-resource-id="${resource.ID}"]`).click();
    await page.getByRole('button',{name:'Resource info',exact:true}).click();
    const input = page.locator('#lightbox-edit-name');
    await expect(input).toHaveValue(prefix);
    await input.fill(prefix+' renamed');
    await input.press('Enter');
    await expect.poll(async () => (await apiClient.getResource(resource.ID)).Name).toBe(prefix+' renamed');
    await page.getByRole('button',{name:'Close info panel',exact:true}).click();
    await expect.poll(() => page.evaluate(() => (window as any).Alpine.store('bulkSelection').selectedEntities()[0]?.Name)).toBe(prefix+' renamed');
    await page.keyboard.press('Escape');

    const mrql = new MRQLPage(page);
    await mrql.navigate();
    await mrql.enterQuery(`type = resource AND name = "${prefix} renamed"`);
    await mrql.executeQuery();
    const resources = page.locator('[data-selection-scope="mrql-resource"]');
    await resources.locator('.card-checkbox').check();
    await resources.locator('[data-lightbox-item]').click();
    await page.getByRole('button',{name:'Resource info',exact:true}).click();
    await expect(input).toHaveValue(prefix+' renamed');
    await input.fill(prefix+' leaves query');
    await input.press('Enter');
    await expect.poll(async () => (await apiClient.getResource(resource.ID)).Name).toBe(prefix+' leaves query');
    await page.getByRole('button',{name:'Close info panel',exact:true}).click();
    await expect(resources.locator('.resource-card')).toHaveCount(0);
    await expect.poll(() => page.evaluate(() => (window as any).Alpine.store('selection:mrql-resource').selectedIds.size)).toBe(0);
});

test('random result pages and Mass Edit share the executed sample', async ({page,apiClient,request}) => {
    const prefix = `review-random-${Date.now()}`;
    const type = await apiClient.createNoteType(prefix);
    await apiClient.createTag(prefix);
    for (let i=0;i<9;i++) await apiClient.createNote({name:`${prefix} ${i}`,noteTypeId:type.ID});
    const mrql = new MRQLPage(page);
    await mrql.navigate();
    await mrql.enterQuery(`type = note AND name ~ "${prefix}" ORDER BY RANDOM() LIMIT 7`);
    await mrql.executeQuery();
    await page.getByLabel('Per page',{exact:false}).selectOption('5');
    const notes = page.locator('[data-selection-scope="mrql-note"]');
    await expect(notes.locator('.note-card')).toHaveCount(5);
    const names = await notes.locator('.card-title').allTextContents();
    await page.getByRole('button',{name:'Next',exact:true}).click();
    await expect(notes.locator('.note-card')).toHaveCount(2);
    names.push(...await notes.locator('.card-title').allTextContents());
    expect(new Set(names.map(name=>name.trim())).size).toBe(7);
    await notes.getByRole('button',{name:'Mass edit all results',exact:true}).click();
    const dialog=page.getByRole('dialog',{name:'Mass edit notes',exact:true});
    await dialog.getByRole('combobox',{name:'Tags to apply',exact:true}).fill(prefix);
    await page.getByRole('option').filter({hasText:prefix}).first().click();
    await dialog.getByRole('button',{name:'Apply',exact:true}).click();
    const confirmation=page.getByRole('alertdialog',{name:'Mass edit',exact:true});
    await expect(confirmation).toContainText('7 notes');
    await confirmation.getByRole('button',{name:'Apply',exact:true}).click();
    await expect(dialog).not.toBeVisible();
    const response = await request.post('/v1/mrql',{data:{query:`type = note AND tags = "${prefix}"`}});
    const result = await response.json();
    expect(result.notes.map((note:{Name:string})=>note.Name).sort()).toEqual(names.map(name=>name.trim()).sort());
});
